import { nanoid } from 'nanoid';

const mockData = [
    {
        make: 'Mini',
        model: 'Cooper JCW GP',
        isNew: true,
        price: 50000,
        id: nanoid(),
    },
    {
        make: 'Ferrari',
        model: 'F50',
        isNew: false,
        price: 3000000,
        id: nanoid(),
    },
    {
        make: 'Subaru',
        model: 'Impreza 22B',
        isNew: false,
        price: 100000,
        id: nanoid(),
    },
    {
        make: 'Audi',
        model: 'RSQ8',
        isNew: true,
        price: 140000,
        id: nanoid(),
    },
    {
        make: 'Aston Martin',
        model: 'Rapide',
        isNew: false,
        price: 60000,
        id: nanoid(),
    },
    {
        make: 'Bentley',
        model: 'Flying Spur',
        isNew: true,
        price: 275000,
        id: nanoid(),
    },
    {
        make: 'Porsche',
        model: '935',
        isNew: true,
        price: 1000000,
        id: nanoid(),
    },
    {
        make: 'Porsche',
        model: 'Cayenne Turbo S',
        isNew: true,
        price: 200000,
        id: nanoid(),
    },
    {
        make: 'Maserati',
        model: 'Coupe',
        isNew: false,
        price: 20000,
        id: nanoid(),
    },
    {
        make: 'Fisker',
        model: 'Karma',
        isNew: false,
        price: 40000,
        id: nanoid(),
    },
    {
        make: 'Ferrari',
        model: 'F8 Tributo',
        isNew: true,
        price: 300000,
        id: nanoid(),
    },
    {
        make: 'GMC',
        model: 'Sierra 3500HD Denali',
        isNew: true,
        price: 80000,
        id: nanoid(),
    },
    {
        make: 'McLaren',
        model: '570S GT4',
        isNew: true,
        price: 200000,
        id: nanoid(),
    },
    {
        make: 'Porsche',
        model: 'Panamera',
        isNew: false,
        price: 30000,
        id: nanoid(),
    },
    {
        make: 'Mercedes',
        model: 'G63 AMG',
        isNew: true,
        price: 200000,
        id: nanoid(),
    },
    {
        make: 'Ford',
        model: 'F-650',
        isNew: true,
        price: 150000,
        id: nanoid(),
    },
    {
        make: 'Pagani',
        model: 'Zonda',
        isNew: false,
        price: 6000000,
        id: nanoid(),
    },
    {
        make: 'Mercedes',
        model: 'G63 AMG 6x6',
        isNew: true,
        price: 1500000,
        id: nanoid(),
    },
    {
        make: 'Ferrari',
        model: '599 GTO',
        isNew: false,
        price: 550000,
        id: nanoid(),
    },
    {
        make: 'Porsche',
        model: '911 Speedster',
        isNew: true,
        price: 300000,
        id: nanoid(),
    },
    {
        make: 'Jaguar',
        model: 'XE SV Project',
        isNew: true,
        price: 200000,
        id: nanoid(),
    },
    {
        make: 'McLaren',
        model: 'GT',
        isNew: true,
        price: 250000,
        id: nanoid(),
    },
    {
        make: 'McLaren',
        model: 'P1',
        isNew: false,
        price: 2000000,
        id: nanoid(),
    },
    {
        make: 'Lexus',
        model: 'LX5709',
        isNew: true,
        price: 95000,
        id: nanoid(),
    },
    {
        make: 'Aston Martin',
        model: 'Superleggera',
        isNew: true,
        price: 350000,
        id: nanoid(),
    },
    {
        make: 'Bentley',
        model: 'Continental GT',
        isNew: true,
        price: 250000,
        id: nanoid(),
    },
    {
        make: 'Bugatti',
        model: 'Chiron',
        isNew: false,
        price: 3000000,
        id: nanoid(),
    },
    {
        make: 'BMW',
        model: 'i3',
        isNew: true,
        price: 50000,
        id: nanoid(),
    },
    {
        make: 'Kia',
        model: 'K900',
        isNew: true,
        price: 60000,
        id: nanoid(),
    },
    {
        make: 'Aston Martin',
        model: 'Vanquish S Volante',
        isNew: true,
        price: 340000,
        id: nanoid(),
    },
];

export default mockData;